//EXPORT && RESULT-订单导出与返回结果
// 获取冻结记录
export const USER_ACCOUNT_PAGE = 'USER_ACCOUNT_PAGE'//PAGE-页数
export const USER_ACCOUNT_EMPTY ='USER_ACCOUNT_EMPTY' //清空列表
/*模板通用上面2个方法*/
export const TPERATION_REQ = 'TPERATION_REQ'
export const TPERATION_RES = 'TPERATION_RES'//用户弹窗操作


// export const RELEASE_REQ = 'RELEASE_REQ'
// export const RELEASE_RES = 'RELEASE_RES'//版本发布

// export const HISTORICALRECORDLIST_REQ = 'HISTORICALRECORDLIST_REQ'
// export const HISTORICALRECORDLIST_RES = 'HISTORICALRECORDLIST_RES'//版本历史记录

// export const VERSIONDETAILS_REQ = 'VERSIONDETAILS_REQ'
// export const VERSIONDETAILS_RES = 'VERSIONDETAILS_RES'//版本详情

export const USERRECEIVE_REQ = 'USERRECEIVE_REQ'
export const USERRECEIVE_RES = 'USERRECEIVE_RES'//用户领取列表

export const USERRECEIVEDETAILS_REQ = 'USERRECEIVEDETAILS_REQ'
export const USERRECEIVEDETAILS_RES = 'USERRECEIVEDETAILS_RES'//用户领取详情

export const DDEVENTDETAILS_REQ = 'DDEVENTDETAILS_REQ'
export const DDEVENTDETAILS_RES = 'DDEVENTDETAILS_RES'//活动详情

export const SHARE_REQ = 'SHARE_REQ'
export const SHARE_RES = 'SHARE_RES'//分享

export const DDLAUNCHEVENT_REQ = 'DDLAUNCHEVENT_REQ'
export const DDLAUNCHEVENT_RES = 'DDLAUNCHEVENT_RES'//发布口令活动

export const DDLISTACTIVITIES_REQ = 'DDLISTACTIVITIES_REQ'
export const DDLISTACTIVITIES_RES = 'DDLISTACTIVITIES_RES'//叮咚令活动列表

export const GENERATE_REQ = 'GENERATE_REQ'
export const GENERATE_RES = 'GENERATE_RES'//生成口令

export const DDCREATE_REQ = 'DDCREATE_REQ'
export const DDCREATE_RES = 'DDCREATE_RES'//保存创建叮咚令

export const SHELVES_REQ = 'SHELVES_REQ'
export const SHELVES_RES = 'SHELVES_RES'//活动下架

export const GETCOUPONS_REQ = 'GETCOUPONS_REQ'
export const GETCOUPONS_RES = 'GETCOUPONS_RES'//进入创建获取优惠券

export const ELISTACTIVITIES_REQ = 'ELISTACTIVITIES_REQ'
export const ELISTACTIVITIES_RES = 'ELISTACTIVITIES_RES'//代言令活动列表

export const DISTRIBUTIONGIFT_REQ = 'DISTRIBUTIONGIFT_REQ'
export const DISTRIBUTIONGIFT_RES = 'DISTRIBUTIONGIFT_RES'//发放礼品

export const REVIEWDETAILS_REQ = 'REVIEWDETAILS_REQ'
export const REVIEWDETAILS_RES = 'REVIEWDETAILS_RES'//审核详情

export const ISSUERECORD_REQ = 'ISSUERECORD_REQ'
export const ISSUERECORD_RES = 'ISSUERECORD_RES'//发放记录

export const TERMINATION_REQ = 'TERMINATION_REQ'
export const TERMINATION_RES = 'TERMINATION_RES'//解约确认

export const CREATEACTIVITY_REQ = 'CREATEACTIVITY_REQ'
export const CREATEACTIVITY_RES = 'CREATEACTIVITY_RES'//创建活动