//EXPORT && RESULT-订单导出与返回结果
// 获取冻结记录
export const USER_ACCOUNT_CONDITION = 'USER_ACCOUNT_CONDITION'; //搜索条件(资金明细)
export const USER_ACCOUNT_RESULT = 'USER_ACCOUNT_RESULT'; //搜索结果(资金明细)
export const USER_ACCOUNT_PAGE = 'USER_ACCOUNT_PAGE'//PAGE-页数

export const USER_ACCOUNT_EMPTY ='USER_ACCOUNT_EMPTY' //清空列表

export const ACTIVITYLIST_REQ = 'ACTIVITYLIST_REQ'
export const ACTIVITYLIST_RES = 'ACTIVITYLIST_RES'//活动列表

export const RAFFLELIST_REQ = 'RAFFLELIST_REQ'
export const RAFFLELIST_RES = 'RAFFLELIST_RES'//大转盘活动列表

export const REGISTEREDLIST_REQ = 'REGISTEREDLIST_REQ'
export const REGISTEREDLIST_RES = 'REGISTEREDLIST_RES'//注册有礼列表

export const INVITATIONLIST_REQ = 'INVITATIONLIST_REQ'
export const INVITATIONLIST_RES = 'INVITATIONLIST_RES'//邀请有礼列表

export const SHOOTLIST_REQ = 'SHOOTLIST_REQ'
export const SHOOTLIST_RES = 'SHOOTLIST_RES'//送拍有礼列表

export const ISSUEDETAILS_REQ = 'ISSUEDETAILS_REQ'
export const ISSUEDETAILS_RES = 'ISSUEDETAILS_RES'//发放详情

export const REGISTEREDDETAILS_REQ = 'REGISTEREDDETAILS_REQ'
export const REGISTEREDDETAILS_RES = 'REGISTEREDDETAILS_RES'//注册有礼详情页

export const INVITATIONDETAILS_REQ = 'INVITATIONDETAILS_REQ'
export const INVITATIONDETAILS_RES = 'INVITATIONDETAILS_RES'//邀请有礼基础奖励详情

export const INVITATIONADDITIONALDETAILS_REQ = 'INVITATIONADDITIONALDETAILS_REQ'
export const INVITATIONADDITIONALDETAILS_RES = 'INVITATIONADDITIONALDETAILS_RES'//邀请额外奖励详情

export const SHOOTDETAILS_REQ = 'SHOOTDETAILS_REQ'
export const SHOOTDETAILS_RES = 'SHOOTDETAILS_RES'//送拍有礼详情

export const LOGISTICS_REQ = 'LOGISTICS_REQ'
export const LOGISTICS_RES = 'LOGISTICS_RES'//填写物流信息详情

export const REMIND_REQ = 'REMIND_REQ'
export const REMIND_RES = 'REMIND_RES'//提醒用户

export const ACT_DETAIL_REQ = 'ACT_DETAIL_REQ'
export const ACT_DETAIL_RES = 'ACT_DETAIL_RES'//审核详情

export const ACT_DETAIL_HANDLE_REQ = 'ACT_DETAIL_HANDLE_REQ'
export const ACT_DETAIL_HANDLE_RES = 'ACT_DETAIL_HANDLE_RES'//审核详情同意驳回