//CONDITION--权限管理搜索条件
//RESULT--权限管理搜索结果
//PAGE-页数
//SN订单
//CONTENT内容
//PASS通过 _RES请求结果
//FAIL驳回 _RES请求结果
export const PERMISSION_ROLE_CONDITION = 'PERMISSION_ROLE_CONDITION';
export const PERMISSION_ROLE_RESULT = 'PERMISSION_ROLE_RESULT';
export const PERMISSION_ROLE_PAGE = 'PERMISSION_ROLE_PAGE'
export const PERMISSION_ROLE_DETAIL_SN = 'PERMISSION_ROLE_DETAIL_SN'
export const PERMISSION_ROLE_DETAIL_CONTENT = 'PERMISSION_ROLE_DETAIL_CONTENT'
export const PERMISSION_ROLE_ADD_ROLE_PASS = 'PERMISSION_ROLE_ADD_ROLE_PASS'
export const PERMISSION_ROLE_GET_PERMISSION = 'PERMISSION_ROLE_GET_PERMISSION'
export const PERMISSION_ROLE_ADD_ROLE_PASS_RES = 'PERMISSION_ROLE_ADD_ROLE_PASS_RES'
export const PERMISSION_ROLE_GET_PERMISSION_RES = 'PERMISSION_ROLE_GET_PERMISSION_RES'
export const PERMISSION_ROLE_GET_PARENT_ROLE = 'PERMISSION_ROLE_GET_PARENT_ROLE'
export const PERMISSION_ROLE_GET_PARENT_ROLE_RES = 'PERMISSION_ROLE_GET_PARENT_ROLE_RES'
//清空列表
export const PERMISSION_ROLE_LIST_EMPTY = 'PERMISSION_ROLE_LIST_EMPTY'

//权限侧边栏列表

export const PERMISSION_ASIDE_LIST = 'PERMISSION_ASIDE_LIST'
export const PERMISSION_ASIDE_LIST_RES = 'PERMISSION_ASIDE_LIST_RES'

