//EXPORT && RESULT-订单导出与返回结果
// 获取冻结记录
export const SETTING_EMPTY ='SETTING_EMPTY' //清空列表
export const SETTING_PAGE = 'SETTING_PAGE'//PAGE-页数
export const USER_SETTING_LISTS_REQ = 'USER_SETTING_LISTS_REQ'//广告列表
export const USER_SETTING_LISTS_RES = 'USER_SETTING_LISTS_RES'
export const USER_SETTING_DETAILS_REQ = 'USER_SETTING_DETAILS_REQ'//广告详情
export const USER_SETTING_DETAILS_RES = 'USER_SETTING_DETAILS_RES'
export const USER_SETTING_PASS_ON_REQ = 'USER_SETTING_PASS_ON_REQ'//广告操作
export const USER_SETTING_PASS_ON_RES = 'USER_SETTING_PASS_ON_RES'

export const MONEY_DETAIL_EXPORT_DATA = 'MONEY_DETAIL_EXPORT_DATA'//导出明细
export const MONEY_DETAIL_EXPORT_DATA_SUCCESS = 'MONEY_DETAIL_EXPORT_DATA_SUCCESS'

// 代言人宣传页
export const ADSPOKESMAN_LIST_REQ = 'ADSPOKESMAN_LIST_REQ' // 列表
export const ADSPOKESMAN_LIST_RES = 'ADSPOKESMAN_LIST_RES'
export const ADSPOKESMAN_PASS_ON_REQ = 'ADSPOKESMAN_PASS_ON_REQ' // 操作
export const ADSPOKESMAN_PASS_ON_RES = 'ADSPOKESMAN_PASS_ON_RES'
export const ADSPOKESMAN_DETAILS_REQ = 'ADSPOKESMAN_DETAILS_REQ' // 详情
export const ADSPOKESMAN_DETAILS_RES = 'ADSPOKESMAN_DETAILS_RES'

// APP发现活动
export const ADFINDACTIVITY_LIST_REQ = 'ADFINDACTIVITY_LIST_REQ' // 发现活动页列表
export const ADFINDACTIVITY_LIST_RES = 'ADFINDACTIVITY_LIST_RES'
export const ADFINDACTIVITY_PASS_ON_REQ = 'ADFINDACTIVITY_PASS_ON_REQ' // 操作
export const ADFINDACTIVITY_PASS_ON_RES = 'ADFINDACTIVITY_PASS_ON_RES'
export const ADFINDACTIVITY_DETAILS_REQ = 'ADFINDACTIVITY_DETAILS_REQ' // 详情
export const ADFINDACTIVITY_DETAILS_RES = 'ADFINDACTIVITY_DETAILS_RES'

// 新闻公告
export const NEWSBULLETIN_LIST_REQ = 'NEWSBULLETIN_LIST_REQ' // 列表
export const NEWSBULLETIN_LIST_RES = 'NEWSBULLETIN_LIST_RES'
export const NEWSBULLETIN_ADD_REQ = 'NEWSBULLETIN_ADD_REQ' // 添加
export const NEWSBULLETIN_ADD_RES = 'NEWSBULLETIN_ADD_RES'
export const NEWSBULLETIN_DELETE_REQ = 'NEWSBULLETIN_DELETE_REQ' // 删除
export const NEWSBULLETIN_DELETE_RES = 'NEWSBULLETIN_DELETE_RES'
export const NEWSBULLETIN_EDIT_REQ = 'NEWSBULLETIN_EDIT_REQ' // 编辑
export const NEWSBULLETIN_EDIT_RES = 'NEWSBULLETIN_EDIT_RES'
export const NEWSBULLETIN_LOWER_REQ = 'NEWSBULLETIN_LOWER_REQ' // 下架
export const NEWSBULLETIN_LOWER_RES = 'NEWSBULLETIN_LOWER_RES'
export const NEWSBULLETIN_DETAIL_REQ = 'NEWSBULLETIN_DETAIL_REQ' // 详情
export const NEWSBULLETIN_DETAIL_RES = 'NEWSBULLETIN_DETAIL_RES'
export const NEWSBULLETIN_RELEASE_REQ = 'NEWSBULLETIN_RELEASE_REQ' // 发布
export const NEWSBULLETIN_RELEASE_RES = 'NEWSBULLETIN_RELEASE_RES'


// 新手指引
export const NOVICEGUIDE_LIST_REQ = 'NOVICEGUIDE_LIST_REQ' // 列表
export const NOVICEGUIDE_LIST_RES = 'NOVICEGUIDE_LIST_RES'
export const NOVICEGUIDE_ADD_REQ = 'NOVICEGUIDE_ADD_REQ' // 添加
export const NOVICEGUIDE_ADD_RES = 'NOVICEGUIDE_ADD_RES'
export const NOVICEGUIDE_PASS_REQ = 'NOVICEGUIDE_PASS_REQ' // 操作
export const NOVICEGUIDE_PASS_RES = 'NOVICEGUIDE_PASS_RES'
export const NOVICEGUIDE_DETAIL_REQ = 'NOVICEGUIDE_DETAIL_REQ' // 详情
export const NOVICEGUIDE_DETAIL_RES = 'NOVICEGUIDE_DETAIL_RES'
export const NOVICEGUIDE_DELETE_REQ = 'NOVICEGUIDE_DELETE_REQ' // 删除
export const NOVICEGUIDE_DELETE_RES = 'NOVICEGUIDE_DELETE_RES'
