// 审核修改邀请人
// CONDITION--用户列表搜索条件
// RESULT--用户列表搜索结果
// PAGE-页数
// AGREEDID-通过id
export const USER_AUDIT_CONDITION = 'USER_AUDIT_CONDITION';
export const USER_AUDIT_RESULT = 'USER_AUDIT_RESULT';
export const USER_AUDIT_PAGE = 'USER_AUDIT_PAGE';
export const USER_AUDIT_AGREEDID = 'USER_AUDIT_AGREEDID';
export const USER_AUDIT_RESULT_SUCCE = 'USER_AUDIT_RESULT_SUCCE';

// 用户列表
// CONDITION--用户列表搜索条件
// RESULT--用户列表搜索结果
// PAGE-页数
export const USER_LIST_CONDITION = 'USER_LIST_CONDITION';
export const USER_LIST_RESULT = 'USER_LIST_RESULT';
export const USER_LIST_PAGE = 'USER_LIST_PAGE';


// 用户详情
// CONDITION--详情搜索条件
// RESULT--用户列表搜索结果
// DELETE_INVITE_USER_CONDITION--删除受邀人请求
// DELETE_INVITE_USER_RESULT--删除受邀人结果
// UPDATE_INVITE_USER_CONDITION--更新受邀人请求
// UPDATE_INVITE_USER_RESULT--更新受邀人结果
// ACCOUNT_INVITE_USER_CONDITION--更新用户账号状态请求
// ACCOUNT_INVITE_USER_RESULT--更新用户账号状态结果
// USER_INFORMATION_1CONDITION--用户信息请求
// USER_INFORMATION_1RESULT--用户信息结果
export const USER_DETAIL_CONDITION = 'USER_LIST_CONDITION';
export const USER_DETAIL_RESULT = 'USER_DETAIL_RESULT';
export const DELETE_INVITE_USER_CONDITION = 'DELETE_INVITE_USER_CONDITION';
export const DELETE_INVITE_USER_RESULT = 'DELETE_INVITE_USER_RESULT';
export const UPDATE_INVITE_USER_CONDITION = 'UPDATE_INVITE_USER_CONDITION';
export const UPDATE_INVITE_USER_RESULT = 'UPDATE_INVITE_USER_RESULT';
export const ACCOUNT_INVITE_USER_CONDITION = 'ACCOUNT_INVITE_USER_CONDITION';
export const ACCOUNT_INVITE_USER_RESULT = 'ACCOUNT_INVITE_USER_RESULT';
export const USER_INFORMATION_1CONDITION = 'USER_INFORMATION_1CONDITION';
export const USER_INFORMATION_1RESULT = 'USER_INFORMATION_1RESULT';

export const USER_INFORMATION_2CONDITION = 'USER_INFORMATION_2CONDITION';
export const USER_INFORMATION_2RESULT = 'USER_INFORMATION_2RESULT';

export const USER_INFORMATION_3CONDITION = 'USER_INFORMATION_3CONDITION';
export const USER_INFORMATION_3RESULT = 'USER_INFORMATION_3RESULT';

// 邀请好友
// CONDITION--邀请好友请求
// RESULT--邀请好友结果invitation
export const INVITATION_CONDITION = 'INVITATION_CONDITION';
export const INVITATION_RESULT = 'INVITATION_RESULT';

// 隐私信息
// CONDITION--邀请好友请求
// RESULT--邀请好友结果privacy
export const PRIVACY_CONDITION = 'PRIVACY_CONDITION';
export const PRIVACY_RESULT = 'PRIVACY_RESULT';
// 清空
export const WEIPAI_MERCHANT_LIST_EMPTY = 'WEIPAI_MERCHANT_LIST_EMPTY';

// 首页dashboard
export const DASHBOARD_CONDITION = 'DASHBOARD_CONDITION';
export const DASHBOARD_RESULT = 'DASHBOARD_RESULT';

// 添加用户
export const ADD_USER_CONMIT = 'ADD_USER_CONMIT';
export const ADDUSER_RESULT = 'ADDUSER_RESULT';

export const ADD_USER_CONMIT_CHECKID = 'ADD_USER_CONMIT_CHECKID'; // 实名认证
export const CHECKID_RESULT = 'CHECKID_RESULT';
