//CONDITION--交易订单列表搜索条件
//RESULT--交易订单列表搜索结果
//PAGE-页数
//SN订单
//CONTENT内容
//PASS通过 _RES请求结果
//FAIL驳回 _RES请求结果
export const AU_MESSAGE_CONDITION = 'AU_MESSAGE_CONDITION';
export const AU_MESSAGE_RESULT = 'AU_MESSAGE_RESULT';
export const AU_MESSAGE_PAGE = 'AU_MESSAGE_PAGE'
export const AU_MESSAGE_LIMIT = 'AU_MESSAGE_LIMIT'
//EDITMESSAGE创建请求
//EDITMESSAGE_RESULT服务器返回结果
export const EDITMESSAGE = 'EDITMESSAGE'
export const EDITMESSAGE_RESULT = 'EDITMESSAGE_RESULT'

//EDITMESSAGE详情请求
//EDITMESSAGE_RESULT详情返回结果details
export const EDITMESSAGE_DETAILS = 'EDITMESSAGE_DETAILS'
export const EDITMESSAGE_DETAILS_RESULT = 'EDITMESSAGE_DETAILS_RESULT'

//清空列表
export const AU_MESSAGE_LIST_EMPTY = 'AU_MESSAGE_LIST_EMPTY'


