//CONDITION--交易订单列表搜索条件
//RESULT--交易订单列表搜索结果
//PAGE-页数
//WEIPAI_MERCHANT_DETAIL_SN订单基本信息
//WEIPAI_MERCHANT_DETAIL_SN_SS,统计信息
//WEIPAI_MERCHANT_DETAIL_SN_SI,商户信息
//WEIPAI_MERCHANT_DETAIL_SN_IL,邀请修改人记录
//CONTENT内容
//PASS通过 _RES请求结果
//FAIL驳回 _RES请求结果
export const WEIPAI_MERCHANT_CONDITION = 'WEIPAI_MERCHANT_CONDITION';
export const WEIPAI_MERCHANT_RESULT = 'WEIPAI_MERCHANT_RESULT';
export const WEIPAI_MERCHANT_PAGE = 'WEIPAI_MERCHANT_PAGE'
export const WEIPAI_MERCHANT_DETAIL_SN = 'WEIPAI_MERCHANT_DETAIL_SN'
export const WEIPAI_MERCHANT_DETAIL_SN_SS = 'WEIPAI_MERCHANT_DETAIL_SN_SS'
export const WEIPAI_MERCHANT_DETAIL_SN_SI = 'WEIPAI_MERCHANT_DETAIL_SN_SI'
export const WEIPAI_MERCHANT_DETAIL_SN_IL = 'WEIPAI_MERCHANT_DETAIL_SN_IL'
export const WEIPAI_MERCHANT_DETAIL_SN_ALL = 'WEIPAI_MERCHANT_DETAIL_SN_ALL'
export const WEIPAI_MERCHANT_DETAIL_CONTENT_ALL = 'WEIPAI_MERCHANT_DETAIL_CONTENT_ALL'
export const WEIPAI_MERCHANT_DETAIL_CONTENT = 'WEIPAI_MERCHANT_DETAIL_CONTENT'
export const WEIPAI_MERCHANT_DETAIL_CONTENT_SS = 'WEIPAI_MERCHANT_DETAIL_CONTENT_SS'
export const WEIPAI_MERCHANT_DETAIL_CONTENT_SI = 'WEIPAI_MERCHANT_DETAIL_CONTENT_SI'
export const WEIPAI_MERCHANT_DETAIL_CONTENT_IL = 'WEIPAI_MERCHANT_DETAIL_CONTENT_IL'
export const WEIPAI_MERCHANT_DETAIL_PASS = 'WEIPAI_MERCHANT_DETAIL_PASS'
export const WEIPAI_MERCHANT_DETAIL_PASS1 = 'WEIPAI_MERCHANT_DETAIL_PASS1'
export const WEIPAI_MERCHANT_DETAIL_FAIL = 'WEIPAI_MERCHANT_DETAIL_FAIL'
export const WEIPAI_MERCHANT_DETAIL_PASS_RES = 'WEIPAI_MERCHANT_DETAIL_PASS_RES'
export const WEIPAI_MERCHANT_DETAIL_PASS_RES1 = 'WEIPAI_MERCHANT_DETAIL_PASS_RES1'
export const WEIPAI_MERCHANT_DETAIL_FAIL_RES = 'WEIPAI_MERCHANT_DETAIL_FAIL_RES'
//清空列表
export const WEIPAI_MERCHANT_LIST_EMPTY = 'WEIPAI_MERCHANT_LIST_EMPTY'

export const DELETE_INVITE_USER_CONDITION1 = 'DELETE_INVITE_USER_CONDITION1';
export const DELETE_INVITE_USER_RESULT1 = 'DELETE_INVITE_USER_RESULT1';
export const UPDATE_INVITE_USER_CONDITION1 = 'UPDATE_INVITE_USER_CONDITION1';
export const UPDATE_INVITE_USER_RESULT1 = 'UPDATE_INVITE_USER_RESULT1';
export const ACCOUNT_INVITE_USER_CONDITION1 = 'ACCOUNT_INVITE_USER_CONDITION1';
export const ACCOUNT_INVITE_USER_RESULT1 = 'ACCOUNT_INVITE_USER_RESULT1';


//收拍管理
export const WITHDRAW_AUCTION_LIST_REQ = 'WITHDRAW_AUCTION_LIST_REQ';//收拍列表
export const WITHDRAW_AUCTION_LIST_RES = 'WITHDRAW_AUCTION_LIST_RES';
export const WITHDRAW_AUCTION_DISPLAY_REQ = 'WITHDRAW_AUCTION_DISPLAY_REQ';//收拍显示/隐藏
export const WITHDRAW_AUCTION_DISPLAY_RES = 'WITHDRAW_AUCTION_DISPLAY_RES';
export const WITHDRAW_AUCTION_SORT_REQ = 'WITHDRAW_AUCTION_SORT_REQ';//收拍排序
export const WITHDRAW_AUCTION_SORT_RES = 'WITHDRAW_AUCTION_SORT_RES';

//微拍记录
export const MODIFY_COMMIT_REQ = 'MODIFY_COMMIT_REQ';//记录提交
export const MODIFY_COMMIT_RES = 'MODIFY_COMMIT_RES';
export const MODIFY_RECORD_REQ = 'MODIFY_RECORD_REQ';//记录显示
export const MODIFY_RECORD_RES = 'MODIFY_RECORD_RES';