//CONDITION--交易订单列表搜索条件
//RESULT--交易订单列表搜索结果
//PAGE-页数
export const TRADING_ORDER_CONDITION = 'TRADING_ORDER_CONDITION';
export const TRADING_ORDER_RESULT = 'TRADING_ORDER_RESULT';
export const TRADING_ORDER_PAGE = 'TRADING_ORDER_PAGE'
export const TRADING_ORDER_DETAIL_SN = 'TRADING_ORDER_DETAIL_SN'
export const TRADING_ORDER_DETAIL_CONTENT = 'TRADING_ORDER_DETAIL_CONTENT'
export const TRADING_ORDER_EXPORT_DATA = 'TRADING_ORDER_EXPORT_DATA'
export const TRADING_ORDER_EXPORT_DATA_SUCCESS = 'TRADING_ORDER_EXPORT_DATA_SUCCESS'
export const WEIPAI_MERCHANT_LIST_EMPTY = 'WEIPAI_MERCHANT_LIST_EMPTY'

