// EXPORT && RESULT-订单导出与返回结果
// 获取冻结记录
export const USER_ACCOUNT_EMPTY = 'USER_ACCOUNT_EMPTY'; // 清空列表
export const USER_ACCOUNT_CONDITION_MON = 'USER_ACCOUNT_CONDITION_MON'; // 搜索条件(资金明细)
export const USER_ACCOUNT_RESULT = 'USER_ACCOUNT_RESULT'; // 搜索结果(资金明细)
export const USER_ACCOUNT_PAGE = 'USER_ACCOUNT_PAGE';// PAGE-页数
export const USER_ACCOUNT_FREEZE_RECORD_REQ = 'USER_ACCOUNT_FREEZE_RECORD_REQ';// 获取冻结记录
export const USER_ACCOUNT_FREEZE_RECORD_RES = 'USER_ACCOUNT_FREEZE_RECORD_RES';
export const USER_ACCOUNT_FREEZE_RECORD_HANDLE_REQ = 'USER_ACCOUNT_FREEZE_RECORD_HANDLE_REQ';// 冻结/解冻操作
export const USER_ACCOUNT_FREEZE_RECORD_HANDLE_RES = 'USER_ACCOUNT_FREEZE_RECORD_HANDLE_RES';
export const USER_COUPON_LISTS_REQ = 'USER_COUPON_LISTS_REQ';// 优惠券列表
export const USER_COUPON_LISTS_RES = 'USER_COUPON_LISTS_RES';
export const USER_COUPON_DETAILS_REQ = 'USER_COUPON_DETAILS_REQ';// 优惠券详情
export const USER_COUPON_DETAILS_RES = 'USER_COUPON_DETAILS_RES';
export const USER_COUPON_PASS_ON_REQ = 'USER_COUPON_PASS_ON_REQ';// 优惠券通过/驳回
export const USER_COUPON_PASS_ON_RES = 'USER_COUPON_PASS_ON_RES';


export const MONEY_DETAIL_EXPORT_DATA = 'MONEY_DETAIL_EXPORT_DATA';// 导出明细
export const MONEY_DETAIL_EXPORT_DATA_SUCCESS = 'MONEY_DETAIL_EXPORT_DATA_SUCCESS';
