//CONDITION--充值补单搜索条件
//RESULT--充值补单搜索结果
//CHARGE_SINGLE_INFO -- 个人信息获取 REQ请求，RES回应
export const CHARGE_SINGLE_CONDITION = 'CHARGE_SINGLE_CONDITION';
export const CHARGE_SINGLE_RESULT = 'CHARGE_SINGLE_RESULT';
export const CHARGE_SINGLE_INFO_REQ = 'CHARGE_SINGLE_RESULT_REQ';
export const CHARGE_SINGLE_INFO_RES = 'CHARGE_SINGLE_RESULT_RES';


