//CONDITION--用户流水搜索条件(提现记录)
//RESULT--用户流水搜索结果
//PAGE-页数
//EXPORT && RESULT-订单导出与返回结果
export const USER_PIPELINE_CONDITION = 'USER_PIPELINE_CONDITION';
export const USER_PIPELINE_RESULT = 'USER_PIPELINE_RESULT';
export const USER_PIPELINE_PAGE = 'USER_PIPELINE_PAGE'
export const USER_PIPELINE_EXPORT = 'USER_PIPELINE_EXPORT'
export const USER_PIPELINE_EXPORT_RESULT = 'USER_PIPELINE_EXPORT_RESULT'


//CONDITION--用户流水搜索条件(充值记录)
//RESULT--用户流水搜索结果
//PAGE-页数
//EXPORT && RESULT-订单导出与返回结果
export const USER_RECHARGE_CONDITION = 'USER_RECHARGE_CONDITION';
export const USER_RECHARGE_RESULT = 'USER_RECHARGE_RESULT';
export const USER_RECHARGE_PAGE = 'USER_RECHARGE_PAGE'
export const USER_RECHARGE_EXPORT = 'USER_RECHARGE_EXPORT'
export const USER_RECHARGE_EXPORT_RESULT = 'USER_RECHARGE_EXPORT_RESULT'


//用户流水-提现记录-详情页



//用户流水-充值记录-详情页
//DETAIL 获取订单信息
//PASS 通过
//FAIL 驳回
export const USER_CHARGE_DETAIL = 'USER_CHARGE_DETAIL'
export const USER_CHARGE_DETAIL_RES = 'USER_CHARGE_DETAIL_RES'

export const USER_CHARGE_DETAIL_PASS = 'USER_CHARGE_DETAIL_PASS'
export const USER_CHARGE_DETAIL_PASS_RES = 'USER_CHARGE_DETAIL_PASS_RES'

export const USER_CHARGE_DETAIL_FAIL = 'USER_CHARGE_DETAIL_FAIL'
export const USER_CHARGE_DETAIL_FAIL_RES = 'USER_CHARGE_DETAIL_FAIL_RES'


//用户流水--线下充值
//SN 订单详情
//PASS 通过

export const USER_OFFLINE_SN = 'USER_OFFLINE_SN'
export const USER_OFFLINE_SN_RES = 'USER_OFFLINE_SN_RES'

export const USER_OFFLINE_SN_PASS = 'USER_OFFLINE_SN_PASS'
export const USER_OFFLINE_SN_PASS_RES = 'USER_OFFLINE_SN_PASS_RES'

export const USER_OFFLINE_SN_ARRIVAL = 'USER_OFFLINE_ARRIVAL' // 确认到账
export const USER_OFFLINE_SN_ARRIVAL_RES = 'USER_OFFLINE_ARRIVAL_RES'