//EXPORT && RESULT-订单导出与返回结果
// 获取冻结记录
export const USER_INTEGRAL_CONDITION = 'USER_INTEGRAL_CONDITION'; //搜索条件(资金明细)
export const USER_INTEGRAL_RESULT = 'USER_INTEGRAL_RESULT'; //搜索结果(资金明细)
export const USER_INTEGRAL_PAGE = 'USER_INTEGRAL_PAGE'//PAGE-页数

export const USER_ACCOUNT_EMPTY ='USER_ACCOUNT_EMPTY' //清空列表

// export const USER_ACCOUNT_FREEZE_RECORD_REQ = 'USER_ACCOUNT_FREEZE_RECORD_REQ'// 获取冻结记录
// export const USER_ACCOUNT_FREEZE_RECORD_RES = 'USER_ACCOUNT_FREEZE_RECORD_RES'
// export const USER_ACCOUNT_FREEZE_RECORD_HANDLE_REQ = 'USER_ACCOUNT_FREEZE_RECORD_HANDLE_REQ'//冻结/解冻操作
// export const USER_ACCOUNT_FREEZE_RECORD_HANDLE_RES = 'USER_ACCOUNT_FREEZE_RECORD_HANDLE_RES'


