// CONDITION--交易订单列表搜索条件
// RESULT--交易订单列表搜索结果
// PAGE-页数
// SN订单
// CONTENT内容
// PASS通过 _RES请求结果
// FAIL驳回 _RES请求结果
export const WEIPAI_ORDER_CONDITION = 'WEIPAI_ORDER_CONDITION';
export const WEIPAI_ORDER_RESULT = 'WEIPAI_ORDER_RESULT';
export const WEIPAI_ORDER_PAGE = 'WEIPAI_ORDER_PAGE';
export const WEIPAI_ORDER_LIMIT = 'WEIPAI_ORDER_LIMIT';
export const WEIPAI_ORDER_DETAILS = 'WEIPAI_ORDER_DETAILS';
export const WEIPAI_ORDER_DETAILS_RESULT = 'WEIPAI_ORDER_DETAILS_RESULT';
export const WEIPAI_ORDER_INFO = 'WEIPAI_ORDER_INFO';
export const WEIPAI_ORDER_INFO_RESULT = 'WEIPAI_ORDER_INFO_RESULT';
export const GROUPBUY_ORDER_DETAILS_RESULT = 'GROUPBUY_ORDER_DETAILS_RESULT';
export const GROUP_ORDER_DETAIL_PASS = 'GROUP_ORDER_DETAIL_PASS';
export const GROUP_ORDER_DETAIL_FAIL = 'GROUP_ORDER_DETAIL_FAIL';
export const GROUP_ORDER_DETAIL_PASS_RES = 'GROUP_ORDER_DETAIL_PASS_RES';
export const GROUP_ORDER_DETAIL_FAIL_RES = 'GROUP_ORDERs_DETAIL_FAIL_RES';



// EDITMESSAGE创建请求
// EDITMESSAGE_RESULT服务器返回结果
// export const EDITMESSAGE = 'EDITMESSAGE'
// export const EDITMESSAGE_RESULT = 'EDITMESSAGE_RESULT'

// //EDITMESSAGE详情请求
// //EDITMESSAGE_RESULT详情返回结果details
// export const EDITMESSAGE_DETAILS = 'EDITMESSAGE_DETAILS'
// export const EDITMESSAGE_DETAILS_RESULT = 'EDITMESSAGE_DETAILS_RESULT'

// //清空列表
export const WEIPAI_ORDER_LIST_EMPTY = 'WEIPAI_ORDER_LIST_EMPTY';


// 团购记录
export const MODIFY_COMMIT_GB_REQ = 'MODIFY_COMMIT_GB_REQ';// 记录提交
export const MODIFY_COMMIT_GB_RES = 'MODIFY_COMMIT_GB_RES';
export const MODIFY_RECORD_GB_REQ = 'MODIFY_RECORD_GB_REQ';// 记录显示
export const MODIFY_RECORD_GB_RES = 'MODIFY_RECORD_GB_RES';

export const ORDER_LIST_EXPORT_DATA = 'ORDER_LIST_EXPORT_DATA'; // 订单列表打印
export const EXPORT_DATA_SUCCESS = 'EXPORT_DATA_SUCCESS';
