//EXPORT && RESULT-订单导出与返回结果
// 获取冻结记录
export const USER_ACCOUNT_PAGE = 'USER_ACCOUNT_PAGE'//PAGE-页数
export const USER_ACCOUNT_EMPTY ='USER_ACCOUNT_EMPTY' //清空列表

export const RELEASE_REQ = 'RELEASE_REQ'
export const RELEASE_RES = 'RELEASE_RES'//版本发布

export const HISTORICALRECORDLIST_REQ = 'HISTORICALRECORDLIST_REQ'
export const HISTORICALRECORDLIST_RES = 'HISTORICALRECORDLIST_RES'//版本历史记录

export const VERSIONDETAILS_REQ = 'VERSIONDETAILS_REQ'
export const VERSIONDETAILS_RES = 'VERSIONDETAILS_RES'//版本详情

